version: "3.3"
services:
    server:
        build: ./server
        ports:
            - "8081:8081"
        depends_on:
            - database
    database:
        image: mysql:latest
        build: ./database
        ports:
            - "8080:8080"
        environment:
                  - MYSQL_ROOT_PASSWORD=1234
