version: "3.3"
networks:
    soundgood:

services:
    mysql:
        image: mysql:latest
        build: ./database
        ports:
            - "8081:8081"
        environment:
            - MYSQL_ROOT_PASSWORD=1234
        networks:
            - soundgood
        volumes:
            - ./database:/host_files
    

